SELECT * FROM TABS;

CREATE TABLE MEMBER
( USER_ID VARCHAR2(500) PRIMARY KEY
, USER_PW VARCHAR2(500) NOT NULL
);

INSERT INTO MEMBER(USER_ID, USER_PW) VALUES('chunkind','wnstjd88');

SELECT * FROM MEMBER;
