SELECT * FROM TABS;


CREATE TABLE MEMBER
( USER_ID VARCHAR2(500) PRIMARY KEY
, USER_PW VARCHAR2(500) NOT NULL
);

CREATE TABLE MEMBER_NAME
( USER_ID VARCHAR2(500) PRIMARY KEY
, USER_NAME VARCHAR2(500) NOT NULL
);

/*MEMBER TABLE에 CRUD*/
SELECT * FROM MEMBER;
INSERT INTO MEMBER(USER_ID, USER_PW) VALUES('chunkind', '88');
UPDATE MEMBER SET USER_PW = 'wnstjd88' WHERE USER_ID = 'chunkind';
DELETE FROM MEMBER WHERE USER_ID = 'chunkind';

/*MEMBER_NAME TABLE에 CRUD*/
SELECT * FROM MEMBER_NAME;
INSERT INTO MEMBER_NAME(USER_ID, USER_NAME) VALUES('chunkind', '준성');
UPDATE MEMBER_NAME SET USER_NAME = '김준성' WHERE USER_ID = 'chunkind';
DELETE FROM MEMBER_NAME WHERE USER_ID = 'chunkind';

/* JOIN */
SELECT A.USER_ID MEMBER_ID
	 , A.USER_PW MEMBER_PW
	 , B.USER_ID MEMBER_NAME_ID
	 , B.USER_NAME MEMBER_NAME_NAME
  FROM MEMBER A, MEMBER_NAME B
 WHERE A.USER_ID = B.USER_ID;

/* SUB QUERY */
SELECT USER_ID
	 , USER_PW
	 , (
	 	 SELECT USER_NAME
	 	   FROM MEMBER_NAME
	 	  WHERE USER_ID = 'chunkind'
	 	) AS USER_NAME
  FROM MEMBER


DROP TABLE MEMBER PURGE;

DROP TABLE MEMBER_NAME PURGE;