SELECT * FROM TABS;

CREATE TABLE MEMBER
( SEQ INTEGER PRIMARY KEY
, NAME VARCHAR2(500) NOT NULL
, ID VARCHAR2(500)
, PW VARCHAR2(500)
, AGE INTEGER
, GENDER CHAR(1)
, TELL VARCHAR2(500)
, REGISTER_DATE DATE
, UPDATE_DATE DATE
);

DROP TABLE MEMBER PURGE;


INSERT INTO MEMBER(SEQ, NAME, ID, PW, AGE, GENDER, TELL, REGISTER_DATE, UPDATE_DATE) VALUES('1', '김준성', 'chunkind', 'wnstjd', 30, 'M', '01040633145', SYSDATE, NULL);
INSERT INTO MEMBER(SEQ, NAME, ID, PW, AGE, GENDER, TELL, REGISTER_DATE, UPDATE_DATE) VALUES('2', '박정하', 'momo0920', 'wjdgk', 25, 'W', '01056604481', SYSDATE, NULL);
INSERT INTO MEMBER(SEQ, NAME, ID, PW, AGE, GENDER, TELL, REGISTER_DATE, UPDATE_DATE) VALUES('3', '최민재', 'cmj', 'alswo', 29, 'M', '01040698901', SYSDATE, NULL);
INSERT INTO MEMBER(SEQ, NAME, ID, PW, AGE, GENDER, TELL, REGISTER_DATE, UPDATE_DATE) VALUES('4', '김새봄', 'ksb_3145', 'toqha', 27, 'W', '01033723145', SYSDATE, NULL);

SELECT * FROM MEMBER;

DELETE FROM MEMBER;

SELECT A.SEQ
	 , A.NAME
	 , A.ID
	 , A.PW
	 , A.AGE
	 , A.GENDER
	 , A.TELL
	 , A.REGISTER_DATE
	 , A.UPDATE_DATE 
	 , B.CHECK_DATE
  FROM MEMBER A, ATTEND B
 WHERE A.ID = B.ID
 ORDER BY B.CHECK_DATE;
 
/* 토요일에 출석한 회원정보 가져오기 */
SELECT A.SEQ
	 , A.NAME
	 , A.ID
	 , A.PW
	 , A.AGE
	 , A.GENDER
	 , A.TELL
	 , A.REGISTER_DATE
	 , A.UPDATE_DATE 
	 , B.CHECK_DATE
	 , CASE TO_CHAR(B.CHECK_DATE, 'D')
	 	WHEN '1' THEN '일요일'
	 	WHEN '2' THEN '월요일'
	 	WHEN '3' THEN '화요일'
	 	WHEN '4' THEN '수요일'
	 	WHEN '5' THEN '목요일'
	 	WHEN '6' THEN '금요일'
	 	WHEN '7' THEN '토요일'
	   END 							AS dayOfTheWeek
  FROM MEMBER A, ATTEND B
 WHERE A.ID = B.ID
   AND TO_CHAR(B.CHECK_DATE, 'D') = 7
 ORDER BY B.CHECK_DATE;
 

/* 날짜기준으로 데이터 가져오기 */
 SELECT DISTINCT TO_CHAR(B.CHECK_DATE, 'YYYY-MM-DD') AS D_DATE
   FROM MEMBER A, ATTEND B 
  WHERE A.ID = B.ID
 
 
/* 53주 구하기 */    
 SELECT TO_DATE((SELECT TO_CHAR(SYSDATE,'YYYY') || '0101' FROM DUAL),'YYYYMMDD') + (ROWNUM-1)*7 AS CHECK_DATE 
   FROM DUAL CONNECT BY LEVEL <=53;
  
/* 365일 구하기 */
 SELECT TO_DATE((SELECT TO_CHAR(SYSDATE,'YYYY') || '0101' FROM DUAL),'YYYYMMDD') + (ROWNUM-1) AS CHECK_DATE 
   FROM DUAL CONNECT BY LEVEL <=365;
 
/* 365일중 토요일만 구하기 */ 
SELECT SUM.*
  FROM (
			SELECT TO_DATE((SELECT TO_CHAR(SYSDATE,'YYYY') || '0101' FROM DUAL),'YYYYMMDD') + (ROWNUM-1) AS CHECK_DATE 
			  FROM DUAL CONNECT BY LEVEL <=365 
	   ) SUM
 WHERE TO_CHAR(CHECK_DATE, 'D') = 7;
 
 
 /* 특정 날짜 부터 현재 날짜까지 토요일만 가져오기. */
 SELECT TO_CHAR(SUM.CHECK_DATE,'YYYY-MM-DD') AS CHECK_DATE
  FROM (
			SELECT TO_DATE((SELECT TO_CHAR(SYSDATE,'YYYY') || '0101' FROM DUAL),'YYYYMMDD') + (ROWNUM-1) AS CHECK_DATE 
				 , TO_CHAR(SYSDATE, 'YYYY-MM-DD') AS CURRENT_DATE
			  FROM DUAL CONNECT BY LEVEL <=365 
	   ) SUM
 WHERE TO_CHAR(CHECK_DATE, 'D') = 7
   AND CHECK_DATE BETWEEN TO_DATE('2017-02-04','YYYY-MM-DD') AND CURRENT_DATE;
   
   
/* 특정 날짜로 부터 회원들의 출석 시간 */
SELECT A.SEQ
	 , A.NAME
	 , A.ID
	 , A.PW
	 , A.AGE
	 , A.GENDER
	 , A.TELL
	 , A.REGISTER_DATE
	 , A.UPDATE_DATE 
	 , TO_CHAR(B.CHECK_DATE, 'YYYY-MM-DD') AS CHECK_DATE
	 , TO_CHAR(B.CHECK_DATE, 'HH24:MI') AS CHECK_TIME
  FROM MEMBER A LEFT JOIN ATTEND B ON(B.ID = A.ID)
 WHERE TO_CHAR(B.CHECK_DATE,'YYYY-MM-DD') = '2017-02-26';
 
 
 SELECT * 
   FROM (
   			SELECT TO_CHAR(SUM.CHECK_DATE,'YYYY-MM-DD') AS CHECK_DATE
			  FROM (
						SELECT TO_DATE((SELECT TO_CHAR(SYSDATE,'YYYY') || '0101' FROM DUAL),'YYYYMMDD') + (ROWNUM-1) AS CHECK_DATE 
							 , TO_CHAR(SYSDATE, 'YYYY-MM-DD') AS CURRENT_DATE
						  FROM DUAL CONNECT BY LEVEL <=365 
				   ) SUM
			 WHERE TO_CHAR(CHECK_DATE, 'D') = 7
			   AND CHECK_DATE BETWEEN TO_DATE('2017-02-04','YYYY-MM-DD') AND CURRENT_DATE
   		) A LEFT JOIN 
   		
   		(
   		
   		) B ON(A.CURRENT_DATE = B.);
 
 
   		
   		
			SELECT A.ID
				 , A.NAME
				 , A.TELL 
				 , C.CHECK_DATE AS GIJUN_DATE
				 , (
				 		SELECT DISTINCT TO_CHAR(B.CHECK_DATE, 'YYYY-MM-DD HH24:MI')
				 		  FROM ATTEND B 
				 		 WHERE A.ID = B.ID
				 		   AND TO_CHAR(B.CHECK_DATE, 'YYYY-MM-DD') = C.CHECK_DATE
				   ) AS ATTEND_DATE
			  FROM MEMBER A
			  	 , (
			  	 		SELECT TO_CHAR(SUM.CHECK_DATE,'YYYY-MM-DD') AS CHECK_DATE
						  FROM (
									SELECT TO_DATE((SELECT TO_CHAR(SYSDATE,'YYYY') || '0101' FROM DUAL),'YYYYMMDD') + (ROWNUM-1) AS CHECK_DATE 
										 , TO_CHAR(SYSDATE, 'YYYY-MM-DD') AS CURRENT_DATE
									  FROM DUAL CONNECT BY LEVEL <=365 
							   ) SUM
						 WHERE TO_CHAR(CHECK_DATE, 'D') = 7
						   AND CHECK_DATE BETWEEN TO_DATE('2017-02-04','YYYY-MM-DD') AND CURRENT_DATE
			  	 	) C;
   		
			  
			  
			  